name: Publish Helm Chart

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Package Chart
        run: |
          helm package drupal-chart
          helm package static-chart
          helm package mysql-backup
          helm repo index . --url https://davyin-co.github.io/k8s-helm-charts/
          
      - name: Publish to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout gh-pages
          git add .
          git commit -m "Update charts"
          git push origin gh-pages

